# Generated by Django 5.2.7 on 2025-11-10 02:14

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DocFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_file', models.CharField(choices=[('PDF', 'pdf'), ('Image', 'image')], max_length=50, verbose_name='Type de Fichier')),
                ('type_language', models.CharField(choices=[('Italien', 'italien'), ('Chinois', 'chinois'), ('Français', 'français'), ('Japonais', 'japonais'), ('Anglais', 'anglais'), ('Espagnol', 'espagnol')], max_length=60, verbose_name='Langue du fichier source')),
                ('button_televerse', models.FileField(max_length=200, upload_to='media', verbose_name='Téléverser votre fichier')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
