# Generated by Django 5.2.7 on 2025-11-12 08:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Tsukiyomi_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='docfile',
            name='path',
            field=models.FilePathField(default='media', path='media'),
            preserve_default=False,
        ),
    ]
