# Generated by Django 5.2.7 on 2025-11-12 21:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Tsukiyomi_app', '0002_docfile_path'),
    ]

    operations = [
        migrations.AlterField(
            model_name='docfile',
            name='path',
            field=models.CharField(default='self.button_televerse.path/%Y/%m/%d'),
        ),
    ]
