# Generated by Django 5.2.7 on 2025-11-12 22:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Tsukiyomi_app', '0003_alter_docfile_path'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='docfile',
            name='path',
        ),
    ]
