# Generated by Django 5.2.7 on 2025-12-12 22:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Tsukiyomi_app', '0005_subscriber'),
    ]

    operations = [
        migrations.RenameField(
            model_name='subscriber',
            old_name='smail',
            new_name='email',
        ),
    ]
