# Generated by Django 5.2.7 on 2025-12-13 19:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Tsukiyomi_app', '0006_rename_smail_subscriber_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='docfile',
            name='button_televerse',
            field=models.FileField(max_length=200, upload_to='media/repository-<django.db.models.fields.related.ForeignKey>', verbose_name='Téléverser votre fichier'),
        ),
    ]
