# Generated by Django 5.2.7 on 2026-02-09 15:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Tsukiyomi_app', '0007_alter_docfile_button_televerse'),
    ]

    operations = [
        migrations.AlterField(
            model_name='docfile',
            name='button_televerse',
            field=models.FileField(max_length=200, upload_to='media', verbose_name='Téléverser votre fichier'),
        ),
    ]
