# Generated by Django 5.2.17 on 2026-10-07 12:13

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Tsukiyomi_app', '0008_alter_docfile_button_televerse'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TranslationJob',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('source_language', models.CharField(choices=[('Italien', 'italien'), ('Chinois', 'chinois'), ('Français', 'français'), ('Japonais', 'japonais'), ('Anglais', 'anglais'), ('Espagnol', 'espagnol')], max_length=60)),
                ('target_language', models.CharField(choices=[('Français', 'français')], default='Français', max_length=60)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('PROCESSING', 'Processing'), ('SUCCEEDED', 'Succeeded'), ('FAILED', 'Failed')], default='PENDING', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
                ('error', models.CharField(blank=True, max_length=255)),
                ('output_file', models.FileField(blank=True, max_length=255, upload_to='')),
                ('source', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Tsukiyomi_app.docfile')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
