# Generated by Django 5.2.7 on 2025-11-13 06:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Tsukiyomi_account_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='usertsukiyomi',
            name='state',
            field=models.BooleanField(default=False),
        ),
    ]
