# Generated by Django 5.2.7 on 2026-02-09 15:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Tsukiyomi_account_app', '0002_usertsukiyomi_state'),
    ]

    operations = [
        migrations.AddField(
            model_name='usertsukiyomi',
            name='state_abonnement',
            field=models.BooleanField(default=False),
        ),
    ]
